/****** Object:  StoredProcedure [TOOLS].[usp_MergeHelper]    Script Date: 6/18/2022 12:32:42 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--Procedure to automate merge/update procedure generation

CREATE PROC [TOOLS].[usp_MergeHelper]
(

 @Arc VARCHAR(100),
 @Target VARCHAR(100), 
 @Base VARCHAR(100),
 @LastCol VARCHAR(100)
 )
 AS
 BEGIN



--{keys}


select string_agg([{keys}],' ') keys
into #K
from 
(
SELECT [{keys}] = CAST('AND t.' +  c.name + ' = s.' + c.name AS NVARCHAR(max)) FROM sys.indexes AS i
iNNER JOIN sys.index_columns AS ic ON ic.index_id = i.index_id AND ic.object_id = i.object_id
INNER JOIN sys.tables AS t ON t.object_id = i.object_id
INNER JOIN sys.columns AS c ON c.object_id = t.object_id AND c.column_id = ic.column_id
INNER JOIN sys.schemas AS s ON s.schema_id = t.schema_id
WHERE i.is_primary_key = 1
and s.name = @Base 
AND t.name = @Target
) k


select string_agg([{ins1}],' ') ins1,string_agg([{ins2}],' ') ins2
into #I
from 
(
SELECT [{ins1}] = CAST(c.name + CASE WHEN c.name = @LastCol THEN '' ELSE ',' END AS NVARCHAR(MAX)),
 [{ins2}] = CAST(' s.' + c.name + CASE WHEN c.name = @LastCol THEN '' ELSE ',' END AS NVARCHAR(MAX))
 
 FROM sys.columns AS c
INNER JOIN sys.tables AS t ON t.object_id = c.object_id
INNER JOIN sys.schemas AS s ON s.schema_id = t.schema_id
WHERE s.name = @Base 
AND t.name = @Target
AND is_identity = 0
AND c.is_computed = 0

) x



SELECT STRING_AGG([{upd}], ' ') upd
INTO #U
FROM 
(
SELECT [{upd}] = CAST('t.' + c.name +  ' = ' +
's.' + c.name + CASE WHEN c.name =@LastCol THEN '' ELSE ',' END AS NVARCHAR(MAX)),c.column_id
 FROM sys.columns AS c
INNER JOIN sys.tables AS t ON t.object_id = c.object_id
INNER JOIN sys.schemas AS s ON s.schema_id = t.schema_id
WHERE s.name = @Base 
AND t.name = @Target
AND is_identity = 0
AND c.is_computed = 0

--don't up date primary keys
AND c.name NOT IN(
SELECT c.name FROM sys.indexes AS i
INNER JOIN sys.index_columns AS ic ON ic.index_id = i.index_id AND ic.object_id = i.object_id
INNER JOIN sys.tables AS t ON t.object_id = i.object_id
INNER JOIN sys.columns AS c ON c.object_id = t.object_id AND c.column_id = ic.column_id
INNER JOIN sys.schemas AS s ON s.schema_id = t.schema_id
WHERE i.is_primary_key = 1
AND s.name = @Base 
AND t.name = @Target
)) upd


DECLARE @stmt VARCHAR(MAX);

SELECT @stmt =


'CREATE PROC ' + @Base + '.[USP_Merge_' + @Target + ']
AS
BEGIN
/* This procedure was generated by [TOOLS].[usp_MergeHelper] */
    MERGE ' + @Base + '.' + @Target + ' AS t
    USING stg.ing' + @Target + ' AS s
    ON 1=1 ' + keys +

' 

    WHEN NOT MATCHED BY TARGET THEN
        INSERT
        (
          ' + ins1 + '
        )
        VALUES
        (
' + ins2 + '            )
    WHEN MATCHED AND s.HashKey <> t.HashKey THEN
        UPDATE SET
' + upd + '
    WHEN NOT MATCHED BY SOURCE THEN
        DELETE
    OUTPUT Deleted.*,
           $action
    INTO ' + @Arc + '.' + @Target + ';

    DELETE FROM ' + @Arc + '.' + @Target + '
    WHERE Id IS NULL;

END'


  FROM #k,#I,#U


--select @stmt
EXECUTE(@stmt)


END
GO


